
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-watcher-sa
  namespace: stradvision

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-watcher-clusterrole
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs: 
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-watcher-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: event-watcher-sa
    namespace: stradvision
roleRef:
  kind: ClusterRole
  name: event-watcher-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: stradvision
data:
  config.yaml: |
    kafka:
      broker:
        - stradvision-kafka-kafka-bootstrap:9092
      topic: event
      timeout: 3s
      retry: 3
      retryBackoff: 100ms
      flushMsg: 1000
      flushTime: 500ms

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: stradvision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: event-watcher-sa
      containers:
        - name: client
          image: stradvision-client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: config-volume
              mountPath: /etc/stradvision
      volumes:
        - name: config-volume
          configMap:
            name: client-config