---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: stradvision
data:
  config.yaml: |
    kafka:
      broker:
        - stradvision-kafka-kafka-bootstrap:9092
      groupID: consumer-group
      topic: event
      rebalanceStrategy: sticky
      dlqTopic: event-dlq
      timeout: 3s
      retry: 3
      retryBackoff: 100ms
      flushMsg: 1000
      flushTime: 500ms

    elasticsearch:
      addresses:
        - https://elasticsearch-master:9200
      user: "elastic"
      pass: "elastic"
      index: "event"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: stradvision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: stradvision-consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: config-volume
              mountPath: /etc/stradvision
      volumes:
        - name: config-volume
          configMap:
            name: consumer-config